name: vnvnc-coin-tapper
region: nyc
services:
  - name: web
    github:
      repo: kirniy1/vnvncbattle
      branch: main
    envs:
      - key: MONGODB_URI
        value: mongodb+srv://kirlichps3:wYRks8y0VujfdQ8G@cluster0.mongodb.net/vnvnc_coin_tapper?retryWrites=true&w=majority
