name: Deploy to DigitalOcean App Platform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to DigitalOcean
      uses: inspire-labs-tms-tech/digital-ocean-deploy-action@v2.0.2
      with:
        app_name: vnvnc-coin-tapper
        token: ${{ secrets.DO_TOKEN }}
        env:
          - key: MONGODB_URI
            value: ${{ secrets.MONGODB_URI }}
