name: Deploy to DigitalOcean App Platform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/app_action@main
        with:
          app_name: vnvnc-coin-tapper
          token: ${{ secrets.dop_v1_84cf87601d71c7c1be12f432b76f414de56e813b838cc0c59365cb3d16b5b134 }}
